export const landmarks = [
  {
    id: '1',
    country: 'France',
    continent: 'Europe',
    name: 'Eiffel Tower',
    from: 'Wikipedia',
    description: `Locally nicknamed "La dame de fer" (French for "Iron Lady"), it was constructed from 1887 to 1889 as the entrance to the 1889 World's Fair and was initially criticised by some of France's leading artists and intellectuals for its design, but it has become a global cultural icon of France and one of the most recognisable structures in the world. The Eiffel Tower is the most visited monument with an entrance fee in the world; 6.91 million people ascended it in 2015.`,
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760038.png',
  }, 
  {
    id: '2',
    country: 'Thailand',
    continent: 'Asia',
    name: 'The Great Buddha',
    from: 'Wikipedia',
    description: `The Great Buddha of Thailand is located in the Wat Muang temple in Ang Thong Province, this statue stands 92 m (300 ft) high, and is 63 m (210 ft) wide. Construction commenced in 1990, and was completed in 2008. It is painted gold and made of concrete. The Buddha is in the seated posture called Maravijaya Attitude. The statue was built following the order of Phra Kru Vibul Arjarakhun, the first abbot of Wat Muang temple, in order to commemorate the King Bhumibol of Thailand.`,
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760059.png',
  },
  {
    id: '3',
    country: 'South Korea',
    continent: 'Asia',
    name: 'Gyeongbokgung Palace',
    from: 'Wikipedia',
    description: `Built in 1395, it is located in northern Seoul, South Korea. The largest of the Five Grand Palaces built by the Joseon dynasty, Gyeongbokgung served as the home of Kings of the Joseon dynasty, the Kings' households, as well as the government of Joseon.`,
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760069.png',
  },
  {
    id: '4',
    country: 'United Kingdom',  
    continent: 'Europe',
    name: 'Palace of Westminster',
    from: 'Wikipedia',
    description: `The Palace of Westminster serves as the meeting place for both the House of Commons and the House of Lords, the two houses of the Parliament of the United Kingdom. Informally known as the Houses of Parliament after its occupants, the Palace lies on the north bank of the River Thames in the City of Westminster, in central London, England.`,
    image_url:'https://cdn-icons-png.flaticon.com/512/760/760043.png',
  },
  {
    id:'5',
    country:'India',  
    continent:'Asia',
    name:'Taj Mahal',
    from: 'Wikipedia',
    description: `The Taj Mahal is an ivory-white marble mausoleum on the right bank of the river Yamuna in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan (reigned from 1628 to 1658) to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself. The tomb is the centrepiece of a 17-hectare (42-acre) complex, which includes a mosque and a guest house, and is set in formal gardens bounded on three sides by a crenellated wall.`,
    image_url: 'https://cdn-icons-png.flaticon.com/128/760/760023.png',
  },
  {
    id: '6',
    country: 'Turkey',
    continent:'Europe',
    name: 'Hagia Sophia',
    from: 'Wikipedia',
    description: `Hagia Sophia is a Late Antique place of worship in Istanbul, designed by the Greek geometers Isidore of Miletus and Anthemius of Tralles. Built in 537 as the patriarchal cathedral of the imperial capital of Constantinople, it was the largest Christian church of the eastern Roman Empire (the Byzantine Empire) and the Eastern Orthodox Church, except during the Latin Empire from 1204 to 1261. In 1453, after the Fall of Constantinople to the Ottoman Empire, it was converted into a mosque.`,
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760049.png',
  },
  {
    id: '7',
    country: 'Indonesia', 
    continent:'Asia',
    name: 'Pura Ulun Danu Bratan',
    from: 'Wikipedia',
    description: `Pura Ulun Danu Beratan, or Pura Bratan, is a major Hindu Shaivite temple in Bali, Indonesia. The temple complex is on the shores of Lake Bratan in the mountains near Bedugul. The water from the lake serves the entire region in the outflow area; downstream there are many smaller water temples that are specific to each irrigation association (subak).`,
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760073.png',
  },
  {
    id: '8',
    country: 'United States',  
    continent: 'America',
    name: 'Statue of Liberty',
    from: 'Wikipedia',
    description: `The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor in New York City, in the United States. The copper statue, a gift from the people of France to the people of the United States, was designed by French sculptor Frédéric Auguste Bartholdi and its metal framework was built by Gustave Eiffel. The statue was dedicated on October 28, 1886.`,
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760051.png',
  },
  {
    id: '9',
    country: 'Spain',  
    continent: 'Europe',
    name: 'Sagrada Familia',
    from: 'Wikipedia',
    description: `The Basílica de la Sagrada Família is a large unfinished Roman Catholic minor basilica in the Eixample district of Barcelona, Catalonia, Spain. Designed by the Spanish architect Antoni Gaudí (1852–1926), his work on the building is part of a UNESCO World Heritage Site. On 7 November 2010, Pope Benedict XVI consecrated the church and proclaimed it a minor basilica.`, 
    image_url:'https://cdn-icons-png.flaticon.com/512/760/760047.png',
  },
  {
    id: '10',
    country: 'Singapore', 
    continent:'Asia',
    name: 'Merlion',
    from: 'Wikipedia',
    description: `The Merlion is the official mascot of Singapore, depicted as a mythical creature with the head of a lion and the body of a fish. Being of prominent symbolic nature to Singapore and Singaporeans in general, it is widely used to represent both the city state and its people in sports teams, advertising, branding, tourism and as a national personification.`,
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760025.png',
  },
  {
    id: '11',
    country: 'Italy', 
    continent:'Europe',
    name:'Tower of Pisa',
    from: 'Wikipedia',
    description: `The Tower of Pisa is the campanile, or freestanding bell tower, of the cathedral of the Italian city of Pisa, known worldwide for its nearly four-degree lean, the result of an unstable foundation. The tower is situated behind the Pisa Cathedral and is the third-oldest structure in the city's Cathedral Square (Piazza del Duomo), after the cathedral and the Pisa Baptistry.`, 
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760022.png',
  },
  {
    id: '12',
    country: 'Russia', 
    continent: 'Europe',
    name: 'Saint Basil',
    from: 'Wikipedia',
    description: `The Cathedral of Vasily the Blessed, commonly known as Saint Basil's Cathedral, is an Orthodox church in Red Square of Moscow, and is one of the most popular cultural symbols of Russia. The building, now a museum, is officially known as the Cathedral of the Intercession of the Most Holy Theotokos on the Moat, or Pokrovsky Cathedral. It was built from 1555 to 1561 on orders from Ivan the Terrible and commemorates the capture of Kazan and Astrakhan.`,
    image_url: 'https://cdn-icons-png.flaticon.com/128/760/760037.png',
  },
  {
    id: '13',
    country: 'Japan',
    continent: 'Asia',
    name: 'Mount Fuji',
    from: 'Wikipedia',
    description: `Mount Fuji is the highest mountain in Japan, standing 3,776.24 m (12,389.2 ft). It is the second-highest volcano located on an island in Asia (after Mount Kerinci on the island of Sumatra), and seventh-highest peak of an island on Earth. Mount Fuji is an active stratovolcano that last erupted from 1707 to 1708. The mountain is located about 100 km (62 mi) southwest of Tokyo and is visible from there on clear days.`,
    image_url: 'https://cdn-icons-png.flaticon.com/128/760/760030.png',
  },
  {
    id: '14',
    country: 'United Arab Emirates',
    continent: 'Asia',
    name: 'Burj Khalifa',
    from: 'Wikipedia',
    description: `The Burj Khalifa, known as the Burj Dubai prior to its inauguration in 2010, is a skyscraper in Dubai, United Arab Emirates. With a total height of 829.8 m (2,722 ft, just over half a mile) and a roof height (excluding antenna, but including a 244 m spire) of 828 m (2,717 ft), the Burj Khalifa has been the tallest structure and building in the world since its topping out in 2009, supplanting Taipei 101, the previous holder of that status.`,
    image_url:'https://cdn-icons-png.flaticon.com/128/760/760045.png',
  },
  {
    id: '15',
    country: 'Greece',
    continent: 'Europe',
    name: 'Acropolis',
    from: 'Wikipedia',
    description: `The Acropolis of Athens is an ancient citadel located on a rocky outcrop above the city of Athens and contains the remains of several ancient buildings of great architectural and historical significance, the most famous being the Parthenon. The term acropolis is generic and there are many other acropoleis in Greece. During ancient times it was known also more properly as Cecropia, after the legendary serpent-man, Cecrops, the supposed first Athenian king.`,
    image_url: 'https://cdn-icons-png.flaticon.com/128/760/760076.png',
  },
  {
    id: '16',
    country: 'Cambodia',
    continent: 'Asia',
    name: 'Angkor Wat',
    from: 'Wikipedia',
    description: `Angkor Wat, located in northwest Cambodia, is the largest religious structure in the form of a temple complex in the world by land area, measuring 162.6 hectares. At the centre of the temple stands a quincunx of four towers surrounding a central spire that rises to a height of 65 m (213 ft) above the ground. The temple has three rectangular galleries, each raised above the next. It lies within an outer wall 3.6 kilometres long and a moat more than five kilometres (three miles) long.`,
    image_url: 'https://cdn-icons-png.flaticon.com/128/760/760057.png',
  },
  {
    id: '17',
    country: 'Malaysia',
    continent: 'Asia',
    name: 'Petronas Tower',
    from: 'Wikipedia',
    description: `The Petronas Towers, or the Petronas Twin Towers are twin skyscrapers in Kuala Lumpur, Malaysia. According to the Council on Tall Buildings and Urban Habitat (CTBUH)'s official definition and ranking, they were the tallest buildings in the world from 1998 to 2004 when they were surpassed by Taipei 101. The Petronas Towers remain the tallest twin towers in the world.`,
    image_url: 'https://cdn-icons-png.flaticon.com/128/760/760032.png',
  },
  {
    id: '18',
    country: 'Netherlands',
    continent: 'Europe',
    name: 'Windmills',
    from: 'holland.com',
    description: `Historically, windmills in Holland served many purposes. The most important probably was pumping water out of the lowlands and back into the rivers beyond the dikes so that the land could be farmed. In the fourteenth century, hollow-post mills were used to drive scoop wheels to drain the wetlands.`,
    image_url:'https://cdn-icons-png.flaticon.com/128/760/760035.png',
  },
  {
    id: '19',
    country: 'China',
    continent: 'Asia',
    name: 'The Great Wall',
    from: 'Wikipedia',
    description: `The Great Wall of China is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe. Several walls were built from as early as the 7th century BC, with selective stretches later joined together by Qin Shi Huang (220–206 BC), the first emperor of China. Little of the Qin wall remains.`,
    image_url:'https://cdn-icons-png.flaticon.com/128/760/760024.png',
  },
  {
    id: '20',
    country: 'Egypt',
    continent: 'Africa',
    name: 'Pyramid',
    from: 'Wikipedia',
    description: `The Egyptian pyramids are ancient masonry structures located in Egypt. Sources cite at least 118 identified Egyptian pyramids. Most were built as tombs for the country's pharaohs and their consorts during the Old and Middle Kingdom periods. The most famous Egyptian pyramids are those found at Giza, on the outskirts of Cairo. Several of the Giza pyramids are counted among the largest structures ever built.`,
    image_url: 'https://cdn-icons-png.flaticon.com/128/760/760065.png',
  },
  {
    id: '21',
    country: 'Germany',
    continent: 'Europe',
    name: 'Cologne Cathedral',
    from: 'Wikipedia',
    description: `Cologne Cathedral is a Catholic cathedral in Cologne, North Rhine-Westphalia. It is the seat of the Archbishop of Cologne and of the administration of the Archdiocese of Cologne. It is a renowned monument of German Catholicism and Gothic architecture and was declared a World Heritage Site in 1996.`,
    image_url: 'https://cdn-icons-png.flaticon.com/128/760/760064.png',
  },
  {
    id: '22',
    country: 'Vatican',
    continent: 'Europe',
    name: `Saint Peter's Basilica`,
    from: 'Wikipedia',
    description: `The Papal Basilica of Saint Peter in the Vatican or simply Saint Peter's Basilica, is a church built in the Renaissance style located in Vatican City, the papal enclave that is within the city of Rome. It was initially planned by Pope Nicholas V and then Pope Julius II to replace the aging Old St. Peter's Basilica, which was built in the 4th century by Roman emperor Constantine the Great. Construction of the present basilica began on 18 April 1506 and was completed on 18 November 1626.`,
    image_url: 'https://cdn-icons-png.flaticon.com/128/760/760056.png',
  },
  {
    id: '23',
    country: 'Mexico',
    continent: 'America',
    name: 'Chichen Itza',
    from: 'Wikipedia',
    description: `Chichen Itza was a major focal point in the Northern Maya Lowlands from the Late Classic (c. AD 600–900) through the Terminal Classic (c. AD 800–900) and into the early portion of the Postclassic period (c. AD 900–1200). The site exhibits a multitude of architectural styles, reminiscent of styles seen in central Mexico and of the Puuc and Chenes styles of the Northern Maya lowlands.`,
    image_url:'https://cdn-icons-png.flaticon.com/512/760/760027.png',
  },
  {
    id: '24',
    country: 'Chile',
    continent: 'America',
    name: 'Ahu Tongariki',
    from: 'Wikipedia',
    description: `Ahu Tongariki is the largest ahu on Easter Island (Rapa Nui). Its moais were toppled during the island's civil wars, and in the twentieth century the ahu was swept inland by a tsunami. It has since been restored and has fifteen moai, including one that weighs eighty-six tonnes, the heaviest ever erected on the island. Ahu Tongariki is one kilometer from Rano Raraku and Poike in the Hotu-iti area of Rapa Nui National Park. All the moai here face sunset during the winter solstice.`,
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760040.png'
  },
  {
    id: '25',
    country: 'South Africa',
    continent: 'Africa',
    name: 'Kradle of Humankind',
    from: 'Wikipedia',
    description: `The paleoanthropological site self-proclaimed as the Cradle of Humankind is located about 50 km (31 mi) northwest of Johannesburg, South Africa, in the Gauteng province. Declared a World Heritage Site by UNESCO in 1999, the site currently occupies 47,000 hectares (180 sq mi) and contains a complex of limestone caves. The registered name of the site in the list of World Heritage Sites is Fossil Hominid Sites of South Africa.`,
    image_url: 'https://cdn-icons-png.flaticon.com/512/760/760050.png',
  }
]

export const continents = [
  {
    id: '1',
    name: 'America',
  },
  {
    id: '2',
    name: 'Europe',
  },
  {
    id: '3',
    name: 'Africa',
  },
  {
    id: '4',
    name: 'Oceania',
  },
  {
    id: '5',
    name: 'Asia',
  },
  {
    id: '6',
    name: 'Antarctica',
  },
]